version: '3.3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  ingress:
    build:
      context: .
      dockerfile: ./core/ingress/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis

  collector-webapp:
    build:
      context: ./collectors/webapp
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - redis
      - ingress
