version: '3.7'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - dokploy-network
  ingress:
    build:
      context: .
      dockerfile: ./core/ingress/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis

  collector-webapp:
    build:
      context: ./collectors/webapp
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - redis
      - ingress

  neo4j:
    image: neo4j
    healthcheck:
      test: "wget -qO- http://localhost:7474 || exit 1"
      interval: 1s
      timeout: 10s
      retries: 10
      start_period: 3s
    ports:
      - "7474:7474" 
      - "${NEO4J_BOLT_PORT:-7687}:${NEO4J_BOLT_PORT:-7687}" # Bolt
    volumes:
      - ./core/stores/data/neo4j:/data
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
